#! /usr/bin/env gosh
(add-load-path "lib")
(add-load-path "../lib")
(add-load-path "../lib/Chapter1")
(use chap1_1)
(use chap2_2)
(use chap2_3)

(define (encode message tree)
  (if (null? message)
      '()
      (append (encode-symbol (car message) tree)
             (encode (cdr message) tree))))

(define (encode-symbol symbol tree)
  (if (leaf? tree)
      '()
      (let ((left (left-branch tree))
            (right (right-branch tree)))
        (cond ((symbol-exists? symbol left)
               (cons 0 (encode-symbol symbol left)))
              ((symbol-exists? symbol right)
               (cons 1 (encode-symbol symbol right)))
              (else (error "Invalid symbol -- ENCODE-SYMBOL" symbol))))))

(define (symbol-exists? symbol tree)
  (if (leaf? tree)
      (eq? symbol (symbol-leaf tree))
      (or (symbol-exists? symbol (left-branch tree))
          (symbol-exists? symbol (right-branch tree)))))
